import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Nav from "../components/Navbar/Nav";

const notoThai = Noto_Sans_Thai({
    subsets: ["thai", "latin"],
    weight: ["100", "300", "400", "500", "700", "900"],
    variable: "--font-noto-thai",
});

export const metadata = {
    title: "Next Fondue.traffy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${notoThai.variable} antialiased`}
            >
                {/* <nav>
                    <Link href="/">Home</Link>
                    <Link href="/dashboard">Dashboard</Link>
                    <Link href="/compare">Compare</Link>
                </nav> */}

                <nav>
                    <Nav />
                </nav>

                {children}

                <footer>
                    <p>&copy; 2025</p>
                </footer>

            </body>

        </html>
    );
}
